apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: k8s-securitymindset-eu-tls
spec:
    secretName: k8s-securitymindset-eu
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: k8s.securitymindset.eu
    dnsNames:
        - k8s.securitymindset.eu
        - www.k8s.securitymindset.eu
    acme:
        config:
            http01:
                ingressClass: nginx
            domains:
                - k8s.securitymindset.eu
                - www.k8s.securitymindset.eu